source 'https://rubygems.org'

gem 'rails', '3.2.11'

gem 'rails-api' 

group :development do
  gem 'rack-cors'
end

group :development, :test do
  gem 'debugger'
  gem 'sqlite3'
end



# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'




# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
